# Generated by Django 2.0.4 on 2018-07-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkAttendance',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('lib_id', models.CharField(db_column='Lib_Id', max_length=50)),
                ('status', models.CharField(db_column='Status', default='INSERT', max_length=100)),
                ('result', models.CharField(db_column='result', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('lib_id', models.CharField(db_column='Lib_Id', max_length=20)),
                ('name', models.CharField(db_column='Name', max_length=500)),
                ('sem', models.IntegerField(db_column='Sem', max_length=10)),
                ('branch', models.CharField(db_column='Branch', max_length=100)),
                ('course', models.CharField(db_column='Course', max_length=100)),
                ('roll_no', models.CharField(db_column='Roll No', max_length=100)),
            ],
        ),
    ]
